version: "3.8"

services:
  remix:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    restart: always

  postgrest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://postgres:password@db:5432/postgres
      PGRST_SERVER_PORT: 8080
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: G3qq2pVU9yVWyLjUvmyNx9MAAAI1kcTv7MbLOJBo
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql

volumes:
  postgres_data:
